### ISSUE TITLE
The Rainbowe is uncompatible with the Pycharm‘s specification or format when list of strings in multiple lines

### ISSUE THREAD

**Issue by heyizhang** [dima74/intellij-indent-rainbow#1]
就是一点儿小瑕疵：
要是按照 Pycharm 建议的 indent format， 那 rainbow indent 就会报红
![image](https://user-images.githubusercontent.com/33022132/70047271-ae67b800-1602-11ea-966e-21d17c101be3.png)

 按照正常缩进， Pycharm 又会给出下波浪线提示： re-format
![image](https://user-images.githubusercontent.com/33022132/70047335-d48d5800-1602-11ea-98cb-5ac933c375d7.png)

要是能兼容一下，更好。最后感谢作者写出这么好的插件！

**Comment by dima74** [comment]
@heyizhang Hello and thank you for reporting! I will try to fix it when I have free time

**Comment by dima74** [comment]
@heyizhang fixed in [version 1.1.0](https://plugins.jetbrains.com/plugin/13308-indent-rainbow/update/74976). Now plugin highlights only indentation (and not alignment):

![image](https://user-images.githubusercontent.com/6505554/71819409-e5673880-309c-11ea-96c3-d1f3ecf88931.png)

(More about indentation vs alignment [here](https://dmitryfrank.com/articles/indent_with_tabs_align_with_spaces).)

---

Thank you and feel free to ask any questions or submit feature requests.

**Comment by heyizhang** [comment]
Thank you very much!
